// App
export const APP_STACK = 'APP_STACK';
export const HOME_SCREEN = 'HOME_SCREEN';
// LOGIN
export const SIGNIN = 'SIGNIN';
//SINGUP 
export const SIGNUP = 'SIGNUP'
// Intro
export const WELCOME_SCREEN = 'WELCOME_SCREEN';
//FORGOT PASSWORD AND USER NAME
export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';
export const FORGOT_PASSWORD_CHANGED_SUCCESSFULLY = 'FORGOT_PASSWORD_CHANGED_SUCCESSFULLY';
export const FORGOT_USER_NAME = 'FORGOT_USER_NAME';
export const FORGOT_USER_NAME_CHANGED_SUCCESSFULLY = 'FORGOT_USER_NAME_CHANGED_SUCCESSFULLY';
export const RESET_PASSWORD = 'RESET_PASSWORD';
export const RESET_PASSWORD_SUCCESSFULLY = 'RESET_PASSWORD_SUCCESSFULLY';