// App
export const APP_STACK = 'APP_STACK';

export const HOME_STACK = 'HOME_STACK'
export const HOME_SCREEN = 'HOME_SCREEN';
export const EXPLORE_SCREEN = 'EXPLORE_SCREEN';
export const BOOKED_SCREEN = 'BOOKED_SCREEN';
export const PROFILE_SCREEN = 'PROFILE_SCREEN';
// LOGIN
export const SIGNIN = 'SIGNIN';
//SINGUP 
export const SIGNUP = 'SIGNUP'
// Intro
export const WELCOME_SCREEN = 'WELCOME_SCREEN';
//FORGOT PASSWORD AND USER NAME
export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';
export const FORGOT_PASSWORD_CHANGED_SUCCESSFULLY = 'FORGOT_PASSWORD_CHANGED_SUCCESSFULLY';
// RESET PASSWORD
export const RESET_PASSWORD = 'RESET_PASSWORD';
export const RESET_PASSWORD_SUCCESSFULLY = 'RESET_PASSWORD_SUCCESSFULLY';